// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI5IWwCO5a_lM8__keHTP7Pp6oZoNWLCw',
    appId: '1:907815545711:web:6214966f8a191fa9bc969a',
    messagingSenderId: '907815545711',
    projectId: 'bmi-calculator-auth-users',
    authDomain: 'bmi-calculator-auth-users.firebaseapp.com',
    storageBucket: 'bmi-calculator-auth-users.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDLiBcMbrLSO3v2mk3YvOR0WytDYGzPMg',
    appId: '1:907815545711:android:097cd98932d99698bc969a',
    messagingSenderId: '907815545711',
    projectId: 'bmi-calculator-auth-users',
    storageBucket: 'bmi-calculator-auth-users.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9we4jkk2nDriEBFQb0b7zrfNl3m5F49E',
    appId: '1:907815545711:ios:9186c84852628937bc969a',
    messagingSenderId: '907815545711',
    projectId: 'bmi-calculator-auth-users',
    storageBucket: 'bmi-calculator-auth-users.appspot.com',
    iosClientId: '907815545711-n2ter8p80n0tvv071p5t16rl0f6sn8p9.apps.googleusercontent.com',
    iosBundleId: 'com.example.mybmi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9we4jkk2nDriEBFQb0b7zrfNl3m5F49E',
    appId: '1:907815545711:ios:9186c84852628937bc969a',
    messagingSenderId: '907815545711',
    projectId: 'bmi-calculator-auth-users',
    storageBucket: 'bmi-calculator-auth-users.appspot.com',
    iosClientId: '907815545711-n2ter8p80n0tvv071p5t16rl0f6sn8p9.apps.googleusercontent.com',
    iosBundleId: 'com.example.mybmi',
  );
}
